#20220908 Abandono la normalización y empiezo de cero
#1 Corroboro que puedo replicar mi mejor marca leaderboard público (OK)
## 20220908_X1 sin Fiscal Bolaños
#2 Pruebo Fiscal Bolaños (Mismo resultado, lo dejo)
#3 Pruebo 200 menos y mejora (Falta sintonía fina)
#20220908_x2_KA113111_8800
#4Pruebo creando ctrx_quarter (NO FUNCIONÓ)
  
##2 Probar la contrucción de algunas features:
#Principal_1[ , campo1 := as.integer( ctrx_quarter >= 49 & mpayroll >= 7043 & (ccaja_ahorro < 4 | is.na(ccaja_ahorro) ) & mpayroll < 1000000 & ( mcheques_depositados < 45000 | is.na(mcheques_depositados) ) & ( Visa_fechaalta < 8986 | is.na(Visa_fechaalta) ) & ( mtarjeta_master_consumo < 77000 | is.na(mtarjeta_master_consumo) ) ]
#Principal_2[ , campo1 := as.integer( ctrx_quarter >= 49 & (mpayroll < 7043 | is.na(mpayroll) ) & mtarjeta_visa_consumo >= 2130 & mpasivos_margen >= 699 & mcaja_ahorro >= 325 & ( cliente_edad < 78 | is.na(cliente_edad) ) & ( ccallcenter_transacciones < 10 | is.na(ccallcenter_transacciones) ) ]
#Principal_3[ , campo1 := as.integer( ctrx_quarter >= 49 & (mpayroll < 7043 | is.na(mpayroll) ) & mtarjeta_visa_consumo >= 2130 & (mpasivos_margen < 699 | is.na(mpasivos_margen) ) & Visa_msaldototal >= 5997 & mrentabilidad_annual >= 11000 & ( Visa_msaldodolares < 3026 | is.na(Visa_msaldodolares) )]
#Principal_4[ , campo1 := as.integer( ctrx_quarter >= 49 & (mpayroll < 7043 | is.na(mpayroll) ) & mtarjeta_visa_consumo >= 2130 & (mpasivos_margen < 699 | is.na(mpasivos_margen) ) & Visa_msaldototal >= 5997 & ( mrentabilidad_annual < 11000 | is.na(mrentabilidad_annual) ) & ( ctrx_quarter < 148 | is.na(ctrx_quarter) )]


#Aplicacion de los mejores hiperparametros encontrados en una bayesiana
#Utilizando clase_binaria =  [  SI = { "BAJA+1", "BAJA+2"} ,  NO="CONTINUA ]

#cargo las librerias que necesito
require("data.table")
require("rpart")
require("rpart.plot")
require("dplyr")


#Aqui se debe poner la carpeta de la materia de SU computadora local
setwd("C:\\gdrive\\UBA2022\\")  #Establezco el Working Directory

#cargo el dataset
dataset  <- fread("./datasets/competencia1_2022.csv")


#creo la clase_binaria SI={ BAJA+1, BAJA+2 }    NO={ CONTINUA }
dataset[ foto_mes==202101, 
         clase_binaria :=  ifelse( clase_ternaria=="CONTINUA", "NO", "SI" ) ]

#Transformo las primeras ramas del árbol en categorías binarias

#Nuevas Features
#dataset[ ,principal_1 := as.integer( ctrx_quarter >= 49 & mpayroll >= 7043 & (ccaja_ahorro < 4 | is.na(ccaja_ahorro) ) & mpayroll < 1000000 & ( mcheques_depositados < 45000 | is.na(mcheques_depositados) ) & ( Visa_fechaalta < 8986 | is.na(Visa_fechaalta) ) & ( mtarjeta_master_consumo < 77000 | is.na(mtarjeta_master_consumo) )) ]
#dataset[ ,principal_3 := as.integer( ctrx_quarter >= 49 & (mpayroll < 7043 | is.na(mpayroll) ) & mtarjeta_visa_consumo >= 2130 & (mpasivos_margen < 699 | is.na(mpasivos_margen) ) & Visa_msaldototal >= 5997 & mrentabilidad_annual >= 11000 & ( Visa_msaldodolares < 3026 | is.na(Visa_msaldodolares) ))]
#dataset[ ,principal_2 := as.integer( ctrx_quarter >= 49 & (mpayroll < 7043 | is.na(mpayroll) ) & mtarjeta_visa_consumo >= 2130 & mpasivos_margen >= 699 & mcaja_ahorro >= 325 & ( cliente_edad < 78 | is.na(cliente_edad) ) & ( ccallcenter_transacciones < 10 | is.na(ccallcenter_transacciones) )) ]
#dataset[ ,principal_4 := as.integer( ctrx_quarter >= 49 & (mpayroll < 7043 | is.na(mpayroll) ) & mtarjeta_visa_consumo >= 2130 & (mpasivos_margen < 699 | is.na(mpasivos_margen) ) & Visa_msaldototal >= 5997 & ( mrentabilidad_annual < 11000 | is.na(mrentabilidad_annual) ) & ( ctrx_quarter < 148 | is.na(ctrx_quarter) ))]


#dataset[ ,ctrx_quarter_bin :=  ifelse( ctrx_quarter >= 49, 1, 0 ) ] 
#dataset[ ,Visa_status_bin :=  ifelse( Visa_status < 8, 0, 1 ) ]
#dataset[ ,Master_status_bin :=  ifelse( Master_status < 8, 0, 1 ) ]
#dataset[ ,mcaja_ahorro_bin :=  ifelse( mcaja_ahorro < 260, 0, 1 ) ]




dtrain  <- dataset[ foto_mes==202101 ]  #defino donde voy a entrenar

#Creo ranking de variables #frankv(DT, cols="x", na.last="keep")

frankv(dtrain, cols="ctrx_quarter", na.last="keep")
frankv(dtrain, cols="mcuentas_saldo", na.last="keep")
frankv(dtrain, cols="cdescubierto_preacordado", na.last="keep")
frankv(dtrain, cols="mprestamos_personales", na.last="keep")
frankv(dtrain, cols="active_quarter", na.last="keep")
frankv(dtrain, cols="cprestamos_personales", na.last="keep")
frankv(dtrain, cols="mcaja_ahorro", na.last="keep")
frankv(dtrain, cols="mcuenta_corriente", na.last="keep")
frankv(dtrain, cols="mactivos_margen", na.last="keep")
frankv(dtrain, cols="ccomisiones_otras", na.last="keep")
frankv(dtrain, cols="mpasivos_margen", na.last="keep")
frankv(dtrain, cols="mtarjeta_visa_consumo", na.last="keep")
frankv(dtrain, cols="Visa_msaldototal", na.last="keep")
frankv(dtrain, cols="Visa_msaldopesos", na.last="keep")
frankv(dtrain, cols="ctarjeta_visa_transacciones", na.last="keep")
frankv(dtrain, cols="mcomisiones", na.last="keep")
frankv(dtrain, cols="cliente_antiguedad", na.last="keep")
frankv(dtrain, cols="mcomisiones_otras", na.last="keep")
frankv(dtrain, cols="mpayroll", na.last="keep")


#Creo nuevas features
dtrain[ ,feature1:= as.integer( ctrx_quarter+ctrx_quarter )]
dtrain[ ,feature2:= as.integer( ctrx_quarter+mpayroll )]
dtrain[ ,feature3:= as.integer( ctrx_quarter+ccaja_ahorro )]
dtrain[ ,feature4:= as.integer( ctrx_quarter+mcheques_depositados )]
dtrain[ ,feature5:= as.integer( ctrx_quarter+Visa_fechaalta )]
dtrain[ ,feature6:= as.integer( ctrx_quarter+mtarjeta_master_consumo )]
dtrain[ ,feature7:= as.integer( ctrx_quarter+ctarjeta_visa_transacciones )]
dtrain[ ,feature8:= as.integer( ctrx_quarter+Visa_mpagospesos )]
dtrain[ ,feature9:= as.integer( ctrx_quarter+mtarjeta_visa_consumo )]
dtrain[ ,feature10:= as.integer( ctrx_quarter+mpasivos_margen )]
dtrain[ ,feature11:= as.integer( ctrx_quarter+ccallcenter_transacciones )]
dtrain[ ,feature12:= as.integer( ctrx_quarter+cliente_edad )]
dtrain[ ,feature13:= as.integer( ctrx_quarter+mcaja_ahorro )]
dtrain[ ,feature14:= as.integer( ctrx_quarter+Visa_msaldototal )]
dtrain[ ,feature15:= as.integer( mpayroll+ctrx_quarter )]
dtrain[ ,feature16:= as.integer( mpayroll+mpayroll )]
dtrain[ ,feature17:= as.integer( mpayroll+ccaja_ahorro )]
dtrain[ ,feature18:= as.integer( mpayroll+mcheques_depositados )]
dtrain[ ,feature19:= as.integer( mpayroll+Visa_fechaalta )]
dtrain[ ,feature20:= as.integer( mpayroll+mtarjeta_master_consumo )]
dtrain[ ,feature21:= as.integer( mpayroll+ctarjeta_visa_transacciones )]
dtrain[ ,feature22:= as.integer( mpayroll+Visa_mpagospesos )]
dtrain[ ,feature23:= as.integer( mpayroll+mtarjeta_visa_consumo )]
dtrain[ ,feature24:= as.integer( mpayroll+mpasivos_margen )]
dtrain[ ,feature25:= as.integer( mpayroll+ccallcenter_transacciones )]
dtrain[ ,feature26:= as.integer( mpayroll+cliente_edad )]
dtrain[ ,feature27:= as.integer( mpayroll+mcaja_ahorro )]
dtrain[ ,feature28:= as.integer( mpayroll+Visa_msaldototal )]
dtrain[ ,feature29:= as.integer( ccaja_ahorro+ctrx_quarter )]
dtrain[ ,feature30:= as.integer( ccaja_ahorro+mpayroll )]
dtrain[ ,feature31:= as.integer( ccaja_ahorro+ccaja_ahorro )]
dtrain[ ,feature32:= as.integer( ccaja_ahorro+mcheques_depositados )]
dtrain[ ,feature33:= as.integer( ccaja_ahorro+Visa_fechaalta )]
dtrain[ ,feature34:= as.integer( ccaja_ahorro+mtarjeta_master_consumo )]
dtrain[ ,feature35:= as.integer( ccaja_ahorro+ctarjeta_visa_transacciones )]
dtrain[ ,feature36:= as.integer( ccaja_ahorro+Visa_mpagospesos )]
dtrain[ ,feature37:= as.integer( ccaja_ahorro+mtarjeta_visa_consumo )]
dtrain[ ,feature38:= as.integer( ccaja_ahorro+mpasivos_margen )]
dtrain[ ,feature39:= as.integer( ccaja_ahorro+ccallcenter_transacciones )]
dtrain[ ,feature40:= as.integer( ccaja_ahorro+cliente_edad )]
dtrain[ ,feature41:= as.integer( ccaja_ahorro+mcaja_ahorro )]
dtrain[ ,feature42:= as.integer( ccaja_ahorro+Visa_msaldototal )]
dtrain[ ,feature43:= as.integer( ccaja_ahorro+ctrx_quarter )]
dtrain[ ,feature44:= as.integer( mcheques_depositados+mpayroll )]
dtrain[ ,feature45:= as.integer( mcheques_depositados+ccaja_ahorro )]
dtrain[ ,feature46:= as.integer( mcheques_depositados+mcheques_depositados )]
dtrain[ ,feature47:= as.integer( mcheques_depositados+Visa_fechaalta )]
dtrain[ ,feature48:= as.integer( mcheques_depositados+mtarjeta_master_consumo )]
dtrain[ ,feature49:= as.integer( mcheques_depositados+ctarjeta_visa_transacciones )]
dtrain[ ,feature50:= as.integer( mcheques_depositados+Visa_mpagospesos )]
dtrain[ ,feature51:= as.integer( mcheques_depositados+mtarjeta_visa_consumo )]
dtrain[ ,feature52:= as.integer( mcheques_depositados+mpasivos_margen )]
dtrain[ ,feature53:= as.integer( mcheques_depositados+ccallcenter_transacciones )]
dtrain[ ,feature54:= as.integer( mcheques_depositados+cliente_edad )]
dtrain[ ,feature55:= as.integer( mcheques_depositados+mcaja_ahorro )]
dtrain[ ,feature56:= as.integer( mcheques_depositados+Visa_msaldototal )]
dtrain[ ,feature57:= as.integer( mcheques_depositados+ctrx_quarter )]
dtrain[ ,feature58:= as.integer( Visa_fechaalta+mpayroll )]
dtrain[ ,feature59:= as.integer( Visa_fechaalta+ccaja_ahorro )]
dtrain[ ,feature60:= as.integer( Visa_fechaalta+mcheques_depositados )]
dtrain[ ,feature61:= as.integer( Visa_fechaalta+Visa_fechaalta )]
dtrain[ ,feature62:= as.integer( Visa_fechaalta+mtarjeta_master_consumo )]
dtrain[ ,feature63:= as.integer( Visa_fechaalta+ctarjeta_visa_transacciones )]
dtrain[ ,feature64:= as.integer( Visa_fechaalta+Visa_mpagospesos )]
dtrain[ ,feature65:= as.integer( Visa_fechaalta+mtarjeta_visa_consumo )]
dtrain[ ,feature66:= as.integer( Visa_fechaalta+mpasivos_margen )]
dtrain[ ,feature67:= as.integer( Visa_fechaalta+ccallcenter_transacciones )]
dtrain[ ,feature68:= as.integer( Visa_fechaalta+cliente_edad )]
dtrain[ ,feature69:= as.integer( Visa_fechaalta+mcaja_ahorro )]
dtrain[ ,feature70:= as.integer( Visa_fechaalta+Visa_msaldototal )]
dtrain[ ,feature71:= as.integer( Visa_fechaalta+ctrx_quarter )]
dtrain[ ,feature72:= as.integer( mtarjeta_master_consumo+mpayroll )]
dtrain[ ,feature73:= as.integer( mtarjeta_master_consumo+ccaja_ahorro )]
dtrain[ ,feature74:= as.integer( mtarjeta_master_consumo+mcheques_depositados )]
dtrain[ ,feature75:= as.integer( mtarjeta_master_consumo+Visa_fechaalta )]
dtrain[ ,feature76:= as.integer( mtarjeta_master_consumo+mtarjeta_master_consumo )]
dtrain[ ,feature77:= as.integer( mtarjeta_master_consumo+ctarjeta_visa_transacciones )]
dtrain[ ,feature78:= as.integer( mtarjeta_master_consumo+Visa_mpagospesos )]
dtrain[ ,feature79:= as.integer( mtarjeta_master_consumo+mtarjeta_visa_consumo )]
dtrain[ ,feature80:= as.integer( mtarjeta_master_consumo+mpasivos_margen )]
dtrain[ ,feature81:= as.integer( mtarjeta_master_consumo+ccallcenter_transacciones )]
dtrain[ ,feature82:= as.integer( mtarjeta_master_consumo+cliente_edad )]
dtrain[ ,feature83:= as.integer( mtarjeta_master_consumo+mcaja_ahorro )]
dtrain[ ,feature84:= as.integer( mtarjeta_master_consumo+Visa_msaldototal )]
dtrain[ ,feature85:= as.integer( mtarjeta_master_consumo+ctrx_quarter )]
dtrain[ ,feature86:= as.integer( ctarjeta_visa_transacciones+mpayroll )]
dtrain[ ,feature87:= as.integer( ctarjeta_visa_transacciones+ccaja_ahorro )]
dtrain[ ,feature88:= as.integer( ctarjeta_visa_transacciones+mcheques_depositados )]
dtrain[ ,feature89:= as.integer( ctarjeta_visa_transacciones+Visa_fechaalta )]
dtrain[ ,feature90:= as.integer( ctarjeta_visa_transacciones+mtarjeta_master_consumo )]
dtrain[ ,feature91:= as.integer( ctarjeta_visa_transacciones+ctarjeta_visa_transacciones )]
dtrain[ ,feature92:= as.integer( ctarjeta_visa_transacciones+Visa_mpagospesos )]
dtrain[ ,feature93:= as.integer( ctarjeta_visa_transacciones+mtarjeta_visa_consumo )]
dtrain[ ,feature94:= as.integer( ctarjeta_visa_transacciones+mpasivos_margen )]
dtrain[ ,feature95:= as.integer( ctarjeta_visa_transacciones+ccallcenter_transacciones )]
dtrain[ ,feature96:= as.integer( ctarjeta_visa_transacciones+cliente_edad )]
dtrain[ ,feature97:= as.integer( ctarjeta_visa_transacciones+mcaja_ahorro )]
dtrain[ ,feature98:= as.integer( ctarjeta_visa_transacciones+Visa_msaldototal )]
dtrain[ ,feature99:= as.integer( ctarjeta_visa_transacciones+ctrx_quarter )]
dtrain[ ,feature100:= as.integer( Visa_mpagospesos+mpayroll )]
dtrain[ ,feature101:= as.integer( Visa_mpagospesos+ccaja_ahorro )]
dtrain[ ,feature102:= as.integer( Visa_mpagospesos+mcheques_depositados )]
dtrain[ ,feature103:= as.integer( Visa_mpagospesos+Visa_fechaalta )]
dtrain[ ,feature104:= as.integer( Visa_mpagospesos+mtarjeta_master_consumo )]
dtrain[ ,feature105:= as.integer( Visa_mpagospesos+ctarjeta_visa_transacciones )]
dtrain[ ,feature106:= as.integer( Visa_mpagospesos+Visa_mpagospesos )]
dtrain[ ,feature107:= as.integer( Visa_mpagospesos+mtarjeta_visa_consumo )]
dtrain[ ,feature108:= as.integer( Visa_mpagospesos+mpasivos_margen )]
dtrain[ ,feature109:= as.integer( Visa_mpagospesos+ccallcenter_transacciones )]
dtrain[ ,feature110:= as.integer( Visa_mpagospesos+cliente_edad )]
dtrain[ ,feature111:= as.integer( Visa_mpagospesos+mcaja_ahorro )]
dtrain[ ,feature112:= as.integer( Visa_mpagospesos+Visa_msaldototal )]
dtrain[ ,feature113:= as.integer( Visa_mpagospesos+ctrx_quarter )]
dtrain[ ,feature114:= as.integer( mtarjeta_visa_consumo+mpayroll )]
dtrain[ ,feature115:= as.integer( mtarjeta_visa_consumo+ccaja_ahorro )]
dtrain[ ,feature116:= as.integer( mtarjeta_visa_consumo+mcheques_depositados )]
dtrain[ ,feature117:= as.integer( mtarjeta_visa_consumo+Visa_fechaalta )]
dtrain[ ,feature118:= as.integer( mtarjeta_visa_consumo+mtarjeta_master_consumo )]
dtrain[ ,feature119:= as.integer( mtarjeta_visa_consumo+ctarjeta_visa_transacciones )]
dtrain[ ,feature120:= as.integer( mtarjeta_visa_consumo+Visa_mpagospesos )]
dtrain[ ,feature121:= as.integer( mtarjeta_visa_consumo+mtarjeta_visa_consumo )]
dtrain[ ,feature122:= as.integer( mtarjeta_visa_consumo+mpasivos_margen )]
dtrain[ ,feature123:= as.integer( mtarjeta_visa_consumo+ccallcenter_transacciones )]
dtrain[ ,feature124:= as.integer( mtarjeta_visa_consumo+cliente_edad )]
dtrain[ ,feature125:= as.integer( mtarjeta_visa_consumo+mcaja_ahorro )]
dtrain[ ,feature126:= as.integer( mtarjeta_visa_consumo+Visa_msaldototal )]
dtrain[ ,feature127:= as.integer( mtarjeta_visa_consumo+ctrx_quarter )]
dtrain[ ,feature128:= as.integer( mpasivos_margen+mpayroll )]
dtrain[ ,feature129:= as.integer( mpasivos_margen+ccaja_ahorro )]
dtrain[ ,feature130:= as.integer( mpasivos_margen+mcheques_depositados )]
dtrain[ ,feature131:= as.integer( mpasivos_margen+Visa_fechaalta )]
dtrain[ ,feature132:= as.integer( mpasivos_margen+mtarjeta_master_consumo )]
dtrain[ ,feature133:= as.integer( mpasivos_margen+ctarjeta_visa_transacciones )]
dtrain[ ,feature134:= as.integer( mpasivos_margen+Visa_mpagospesos )]
dtrain[ ,feature135:= as.integer( mpasivos_margen+mtarjeta_visa_consumo )]
dtrain[ ,feature136:= as.integer( mpasivos_margen+mpasivos_margen )]
dtrain[ ,feature137:= as.integer( mpasivos_margen+ccallcenter_transacciones )]
dtrain[ ,feature138:= as.integer( mpasivos_margen+cliente_edad )]
dtrain[ ,feature139:= as.integer( mpasivos_margen+mcaja_ahorro )]
dtrain[ ,feature140:= as.integer( mpasivos_margen+Visa_msaldototal )]
dtrain[ ,feature141:= as.integer( mpasivos_margen+ctrx_quarter )]
dtrain[ ,feature142:= as.integer( ccallcenter_transacciones+mpayroll )]
dtrain[ ,feature143:= as.integer( ccallcenter_transacciones+ccaja_ahorro )]
dtrain[ ,feature144:= as.integer( ccallcenter_transacciones+mcheques_depositados )]
dtrain[ ,feature145:= as.integer( ccallcenter_transacciones+Visa_fechaalta )]
dtrain[ ,feature146:= as.integer( ccallcenter_transacciones+mtarjeta_master_consumo )]
dtrain[ ,feature147:= as.integer( ccallcenter_transacciones+ctarjeta_visa_transacciones )]
dtrain[ ,feature148:= as.integer( ccallcenter_transacciones+Visa_mpagospesos )]
dtrain[ ,feature149:= as.integer( ccallcenter_transacciones+mtarjeta_visa_consumo )]
dtrain[ ,feature150:= as.integer( ccallcenter_transacciones+mpasivos_margen )]
dtrain[ ,feature151:= as.integer( ccallcenter_transacciones+ccallcenter_transacciones )]
dtrain[ ,feature152:= as.integer( ccallcenter_transacciones+cliente_edad )]
dtrain[ ,feature153:= as.integer( ccallcenter_transacciones+mcaja_ahorro )]
dtrain[ ,feature154:= as.integer( ccallcenter_transacciones+Visa_msaldototal )]
dtrain[ ,feature155:= as.integer( ccallcenter_transacciones+ctrx_quarter )]
dtrain[ ,feature156:= as.integer( cliente_edad+mpayroll )]
dtrain[ ,feature157:= as.integer( cliente_edad+ccaja_ahorro )]
dtrain[ ,feature158:= as.integer( cliente_edad+mcheques_depositados )]
dtrain[ ,feature159:= as.integer( cliente_edad+Visa_fechaalta )]
dtrain[ ,feature160:= as.integer( cliente_edad+mtarjeta_master_consumo )]
dtrain[ ,feature161:= as.integer( cliente_edad+ctarjeta_visa_transacciones )]
dtrain[ ,feature162:= as.integer( cliente_edad+Visa_mpagospesos )]
dtrain[ ,feature163:= as.integer( cliente_edad+mtarjeta_visa_consumo )]
dtrain[ ,feature164:= as.integer( cliente_edad+mpasivos_margen )]
dtrain[ ,feature165:= as.integer( cliente_edad+ccallcenter_transacciones )]
dtrain[ ,feature166:= as.integer( cliente_edad+cliente_edad )]
dtrain[ ,feature167:= as.integer( cliente_edad+mcaja_ahorro )]
dtrain[ ,feature168:= as.integer( cliente_edad+Visa_msaldototal )]
dtrain[ ,feature169:= as.integer( cliente_edad+ctrx_quarter )]
dtrain[ ,feature170:= as.integer( mcaja_ahorro+mpayroll )]
dtrain[ ,feature171:= as.integer( mcaja_ahorro+ccaja_ahorro )]
dtrain[ ,feature172:= as.integer( mcaja_ahorro+mcheques_depositados )]
dtrain[ ,feature173:= as.integer( mcaja_ahorro+Visa_fechaalta )]
dtrain[ ,feature174:= as.integer( mcaja_ahorro+mtarjeta_master_consumo )]
dtrain[ ,feature175:= as.integer( mcaja_ahorro+ctarjeta_visa_transacciones )]
dtrain[ ,feature176:= as.integer( mcaja_ahorro+Visa_mpagospesos )]
dtrain[ ,feature177:= as.integer( mcaja_ahorro+mtarjeta_visa_consumo )]
dtrain[ ,feature178:= as.integer( mcaja_ahorro+mpasivos_margen )]
dtrain[ ,feature179:= as.integer( mcaja_ahorro+ccallcenter_transacciones )]
dtrain[ ,feature180:= as.integer( mcaja_ahorro+cliente_edad )]
dtrain[ ,feature181:= as.integer( mcaja_ahorro+mcaja_ahorro )]
dtrain[ ,feature182:= as.integer( mcaja_ahorro+Visa_msaldototal )]
dtrain[ ,feature183:= as.integer( mcaja_ahorro+ctrx_quarter )]
dtrain[ ,feature184:= as.integer( Visa_msaldototal+mpayroll )]
dtrain[ ,feature185:= as.integer( Visa_msaldototal+ccaja_ahorro )]
dtrain[ ,feature186:= as.integer( Visa_msaldototal+mcheques_depositados )]
dtrain[ ,feature187:= as.integer( Visa_msaldototal+Visa_fechaalta )]
dtrain[ ,feature188:= as.integer( Visa_msaldototal+mtarjeta_master_consumo )]
dtrain[ ,feature189:= as.integer( Visa_msaldototal+ctarjeta_visa_transacciones )]
dtrain[ ,feature190:= as.integer( Visa_msaldototal+Visa_mpagospesos )]
dtrain[ ,feature191:= as.integer( Visa_msaldototal+mtarjeta_visa_consumo )]
dtrain[ ,feature192:= as.integer( Visa_msaldototal+mpasivos_margen )]
dtrain[ ,feature193:= as.integer( Visa_msaldototal+ccallcenter_transacciones )]
dtrain[ ,feature194:= as.integer( Visa_msaldototal+cliente_edad )]
dtrain[ ,feature195:= as.integer( Visa_msaldototal+mcaja_ahorro )]
dtrain[ ,feature196:= as.integer( Visa_msaldototal+Visa_msaldototal )]
dtrain[ ,feature197:= as.integer( ctrx_quarter*ctrx_quarter )]
dtrain[ ,feature198:= as.integer( ctrx_quarter*mpayroll )]
dtrain[ ,feature199:= as.integer( ctrx_quarter*ccaja_ahorro )]
dtrain[ ,feature200:= as.integer( ctrx_quarter*mcheques_depositados )]
dtrain[ ,feature201:= as.integer( ctrx_quarter*Visa_fechaalta )]
dtrain[ ,feature202:= as.integer( ctrx_quarter*mtarjeta_master_consumo )]
dtrain[ ,feature203:= as.integer( ctrx_quarter*ctarjeta_visa_transacciones )]
dtrain[ ,feature204:= as.integer( ctrx_quarter*Visa_mpagospesos )]
dtrain[ ,feature205:= as.integer( ctrx_quarter*mtarjeta_visa_consumo )]
dtrain[ ,feature206:= as.integer( ctrx_quarter*mpasivos_margen )]
dtrain[ ,feature207:= as.integer( ctrx_quarter*ccallcenter_transacciones )]
dtrain[ ,feature208:= as.integer( ctrx_quarter*cliente_edad )]
dtrain[ ,feature209:= as.integer( ctrx_quarter*mcaja_ahorro )]
dtrain[ ,feature210:= as.integer( ctrx_quarter*Visa_msaldototal )]
dtrain[ ,feature211:= as.integer( mpayroll*ctrx_quarter )]
dtrain[ ,feature212:= as.integer( mpayroll*mpayroll )]
dtrain[ ,feature213:= as.integer( mpayroll*ccaja_ahorro )]
dtrain[ ,feature214:= as.integer( mpayroll*mcheques_depositados )]
dtrain[ ,feature215:= as.integer( mpayroll*Visa_fechaalta )]
dtrain[ ,feature216:= as.integer( mpayroll*mtarjeta_master_consumo )]
dtrain[ ,feature217:= as.integer( mpayroll*ctarjeta_visa_transacciones )]
dtrain[ ,feature218:= as.integer( mpayroll*Visa_mpagospesos )]
dtrain[ ,feature219:= as.integer( mpayroll*mtarjeta_visa_consumo )]
dtrain[ ,feature220:= as.integer( mpayroll*mpasivos_margen )]
dtrain[ ,feature221:= as.integer( mpayroll*ccallcenter_transacciones )]
dtrain[ ,feature222:= as.integer( mpayroll*cliente_edad )]
dtrain[ ,feature223:= as.integer( mpayroll*mcaja_ahorro )]
dtrain[ ,feature224:= as.integer( mpayroll*Visa_msaldototal )]
dtrain[ ,feature225:= as.integer( ccaja_ahorro*ctrx_quarter )]
dtrain[ ,feature226:= as.integer( ccaja_ahorro*mpayroll )]
dtrain[ ,feature227:= as.integer( ccaja_ahorro*ccaja_ahorro )]
dtrain[ ,feature228:= as.integer( ccaja_ahorro*mcheques_depositados )]
dtrain[ ,feature229:= as.integer( ccaja_ahorro*Visa_fechaalta )]
dtrain[ ,feature230:= as.integer( ccaja_ahorro*mtarjeta_master_consumo )]
dtrain[ ,feature231:= as.integer( ccaja_ahorro*ctarjeta_visa_transacciones )]
dtrain[ ,feature232:= as.integer( ccaja_ahorro*Visa_mpagospesos )]
dtrain[ ,feature233:= as.integer( ccaja_ahorro*mtarjeta_visa_consumo )]
dtrain[ ,feature234:= as.integer( ccaja_ahorro*mpasivos_margen )]
dtrain[ ,feature235:= as.integer( ccaja_ahorro*ccallcenter_transacciones )]
dtrain[ ,feature236:= as.integer( ccaja_ahorro*cliente_edad )]
dtrain[ ,feature237:= as.integer( ccaja_ahorro*mcaja_ahorro )]
dtrain[ ,feature238:= as.integer( ccaja_ahorro*Visa_msaldototal )]
dtrain[ ,feature239:= as.integer( ccaja_ahorro*ctrx_quarter )]
dtrain[ ,feature240:= as.integer( mcheques_depositados*mpayroll )]
dtrain[ ,feature241:= as.integer( mcheques_depositados*ccaja_ahorro )]
dtrain[ ,feature242:= as.integer( mcheques_depositados*mcheques_depositados )]
dtrain[ ,feature243:= as.integer( mcheques_depositados*Visa_fechaalta )]
dtrain[ ,feature244:= as.integer( mcheques_depositados*mtarjeta_master_consumo )]
dtrain[ ,feature245:= as.integer( mcheques_depositados*ctarjeta_visa_transacciones )]
dtrain[ ,feature246:= as.integer( mcheques_depositados*Visa_mpagospesos )]
dtrain[ ,feature247:= as.integer( mcheques_depositados*mtarjeta_visa_consumo )]
dtrain[ ,feature248:= as.integer( mcheques_depositados*mpasivos_margen )]
dtrain[ ,feature249:= as.integer( mcheques_depositados*ccallcenter_transacciones )]
dtrain[ ,feature250:= as.integer( mcheques_depositados*cliente_edad )]
dtrain[ ,feature251:= as.integer( mcheques_depositados*mcaja_ahorro )]
dtrain[ ,feature252:= as.integer( mcheques_depositados*Visa_msaldototal )]
dtrain[ ,feature253:= as.integer( mcheques_depositados*ctrx_quarter )]
dtrain[ ,feature254:= as.integer( Visa_fechaalta*mpayroll )]
dtrain[ ,feature255:= as.integer( Visa_fechaalta*ccaja_ahorro )]
dtrain[ ,feature256:= as.integer( Visa_fechaalta*mcheques_depositados )]
dtrain[ ,feature257:= as.integer( Visa_fechaalta*Visa_fechaalta )]
dtrain[ ,feature258:= as.integer( Visa_fechaalta*mtarjeta_master_consumo )]
dtrain[ ,feature259:= as.integer( Visa_fechaalta*ctarjeta_visa_transacciones )]
dtrain[ ,feature260:= as.integer( Visa_fechaalta*Visa_mpagospesos )]
dtrain[ ,feature261:= as.integer( Visa_fechaalta*mtarjeta_visa_consumo )]
dtrain[ ,feature262:= as.integer( Visa_fechaalta*mpasivos_margen )]
dtrain[ ,feature263:= as.integer( Visa_fechaalta*ccallcenter_transacciones )]
dtrain[ ,feature264:= as.integer( Visa_fechaalta*cliente_edad )]
dtrain[ ,feature265:= as.integer( Visa_fechaalta*mcaja_ahorro )]
dtrain[ ,feature266:= as.integer( Visa_fechaalta*Visa_msaldototal )]
dtrain[ ,feature267:= as.integer( Visa_fechaalta*ctrx_quarter )]
dtrain[ ,feature268:= as.integer( mtarjeta_master_consumo*mpayroll )]
dtrain[ ,feature269:= as.integer( mtarjeta_master_consumo*ccaja_ahorro )]
dtrain[ ,feature270:= as.integer( mtarjeta_master_consumo*mcheques_depositados )]
dtrain[ ,feature271:= as.integer( mtarjeta_master_consumo*Visa_fechaalta )]
dtrain[ ,feature272:= as.integer( mtarjeta_master_consumo*mtarjeta_master_consumo )]
dtrain[ ,feature273:= as.integer( mtarjeta_master_consumo*ctarjeta_visa_transacciones )]
dtrain[ ,feature274:= as.integer( mtarjeta_master_consumo*Visa_mpagospesos )]
dtrain[ ,feature275:= as.integer( mtarjeta_master_consumo*mtarjeta_visa_consumo )]
dtrain[ ,feature276:= as.integer( mtarjeta_master_consumo*mpasivos_margen )]
dtrain[ ,feature277:= as.integer( mtarjeta_master_consumo*ccallcenter_transacciones )]
dtrain[ ,feature278:= as.integer( mtarjeta_master_consumo*cliente_edad )]
dtrain[ ,feature279:= as.integer( mtarjeta_master_consumo*mcaja_ahorro )]
dtrain[ ,feature280:= as.integer( mtarjeta_master_consumo*Visa_msaldototal )]
dtrain[ ,feature281:= as.integer( mtarjeta_master_consumo*ctrx_quarter )]
dtrain[ ,feature282:= as.integer( ctarjeta_visa_transacciones*mpayroll )]
dtrain[ ,feature283:= as.integer( ctarjeta_visa_transacciones*ccaja_ahorro )]
dtrain[ ,feature284:= as.integer( ctarjeta_visa_transacciones*mcheques_depositados )]
dtrain[ ,feature285:= as.integer( ctarjeta_visa_transacciones*Visa_fechaalta )]
dtrain[ ,feature286:= as.integer( ctarjeta_visa_transacciones*mtarjeta_master_consumo )]
dtrain[ ,feature287:= as.integer( ctarjeta_visa_transacciones*ctarjeta_visa_transacciones )]
dtrain[ ,feature288:= as.integer( ctarjeta_visa_transacciones*Visa_mpagospesos )]
dtrain[ ,feature289:= as.integer( ctarjeta_visa_transacciones*mtarjeta_visa_consumo )]
dtrain[ ,feature290:= as.integer( ctarjeta_visa_transacciones*mpasivos_margen )]
dtrain[ ,feature291:= as.integer( ctarjeta_visa_transacciones*ccallcenter_transacciones )]
dtrain[ ,feature292:= as.integer( ctarjeta_visa_transacciones*cliente_edad )]
dtrain[ ,feature293:= as.integer( ctarjeta_visa_transacciones*mcaja_ahorro )]
dtrain[ ,feature294:= as.integer( ctarjeta_visa_transacciones*Visa_msaldototal )]
dtrain[ ,feature295:= as.integer( ctarjeta_visa_transacciones*ctrx_quarter )]
dtrain[ ,feature296:= as.integer( Visa_mpagospesos*mpayroll )]
dtrain[ ,feature297:= as.integer( Visa_mpagospesos*ccaja_ahorro )]
dtrain[ ,feature298:= as.integer( Visa_mpagospesos*mcheques_depositados )]
dtrain[ ,feature299:= as.integer( Visa_mpagospesos*Visa_fechaalta )]
dtrain[ ,feature300:= as.integer( Visa_mpagospesos*mtarjeta_master_consumo )]
dtrain[ ,feature301:= as.integer( Visa_mpagospesos*ctarjeta_visa_transacciones )]
dtrain[ ,feature302:= as.integer( Visa_mpagospesos*Visa_mpagospesos )]
dtrain[ ,feature303:= as.integer( Visa_mpagospesos*mtarjeta_visa_consumo )]
dtrain[ ,feature304:= as.integer( Visa_mpagospesos*mpasivos_margen )]
dtrain[ ,feature305:= as.integer( Visa_mpagospesos*ccallcenter_transacciones )]
dtrain[ ,feature306:= as.integer( Visa_mpagospesos*cliente_edad )]
dtrain[ ,feature307:= as.integer( Visa_mpagospesos*mcaja_ahorro )]
dtrain[ ,feature308:= as.integer( Visa_mpagospesos*Visa_msaldototal )]
dtrain[ ,feature309:= as.integer( Visa_mpagospesos*ctrx_quarter )]
dtrain[ ,feature310:= as.integer( mtarjeta_visa_consumo*mpayroll )]
dtrain[ ,feature311:= as.integer( mtarjeta_visa_consumo*ccaja_ahorro )]
dtrain[ ,feature312:= as.integer( mtarjeta_visa_consumo*mcheques_depositados )]
dtrain[ ,feature313:= as.integer( mtarjeta_visa_consumo*Visa_fechaalta )]
dtrain[ ,feature314:= as.integer( mtarjeta_visa_consumo*mtarjeta_master_consumo )]
dtrain[ ,feature315:= as.integer( mtarjeta_visa_consumo*ctarjeta_visa_transacciones )]
dtrain[ ,feature316:= as.integer( mtarjeta_visa_consumo*Visa_mpagospesos )]
dtrain[ ,feature317:= as.integer( mtarjeta_visa_consumo*mtarjeta_visa_consumo )]
dtrain[ ,feature318:= as.integer( mtarjeta_visa_consumo*mpasivos_margen )]
dtrain[ ,feature319:= as.integer( mtarjeta_visa_consumo*ccallcenter_transacciones )]
dtrain[ ,feature320:= as.integer( mtarjeta_visa_consumo*cliente_edad )]
dtrain[ ,feature321:= as.integer( mtarjeta_visa_consumo*mcaja_ahorro )]
dtrain[ ,feature322:= as.integer( mtarjeta_visa_consumo*Visa_msaldototal )]
dtrain[ ,feature323:= as.integer( mtarjeta_visa_consumo*ctrx_quarter )]
dtrain[ ,feature324:= as.integer( mpasivos_margen*mpayroll )]
dtrain[ ,feature325:= as.integer( mpasivos_margen*ccaja_ahorro )]
dtrain[ ,feature326:= as.integer( mpasivos_margen*mcheques_depositados )]
dtrain[ ,feature327:= as.integer( mpasivos_margen*Visa_fechaalta )]
dtrain[ ,feature328:= as.integer( mpasivos_margen*mtarjeta_master_consumo )]
dtrain[ ,feature329:= as.integer( mpasivos_margen*ctarjeta_visa_transacciones )]
dtrain[ ,feature330:= as.integer( mpasivos_margen*Visa_mpagospesos )]
dtrain[ ,feature331:= as.integer( mpasivos_margen*mtarjeta_visa_consumo )]
dtrain[ ,feature332:= as.integer( mpasivos_margen*mpasivos_margen )]
dtrain[ ,feature333:= as.integer( mpasivos_margen*ccallcenter_transacciones )]
dtrain[ ,feature334:= as.integer( mpasivos_margen*cliente_edad )]
dtrain[ ,feature335:= as.integer( mpasivos_margen*mcaja_ahorro )]
dtrain[ ,feature336:= as.integer( mpasivos_margen*Visa_msaldototal )]
dtrain[ ,feature337:= as.integer( mpasivos_margen*ctrx_quarter )]
dtrain[ ,feature338:= as.integer( ccallcenter_transacciones*mpayroll )]
dtrain[ ,feature339:= as.integer( ccallcenter_transacciones*ccaja_ahorro )]
dtrain[ ,feature340:= as.integer( ccallcenter_transacciones*mcheques_depositados )]
dtrain[ ,feature341:= as.integer( ccallcenter_transacciones*Visa_fechaalta )]
dtrain[ ,feature342:= as.integer( ccallcenter_transacciones*mtarjeta_master_consumo )]
dtrain[ ,feature343:= as.integer( ccallcenter_transacciones*ctarjeta_visa_transacciones )]
dtrain[ ,feature344:= as.integer( ccallcenter_transacciones*Visa_mpagospesos )]
dtrain[ ,feature345:= as.integer( ccallcenter_transacciones*mtarjeta_visa_consumo )]
dtrain[ ,feature346:= as.integer( ccallcenter_transacciones*mpasivos_margen )]
dtrain[ ,feature347:= as.integer( ccallcenter_transacciones*ccallcenter_transacciones )]
dtrain[ ,feature348:= as.integer( ccallcenter_transacciones*cliente_edad )]
dtrain[ ,feature349:= as.integer( ccallcenter_transacciones*mcaja_ahorro )]
dtrain[ ,feature350:= as.integer( ccallcenter_transacciones*Visa_msaldototal )]
dtrain[ ,feature351:= as.integer( ccallcenter_transacciones*ctrx_quarter )]
dtrain[ ,feature352:= as.integer( cliente_edad*mpayroll )]
dtrain[ ,feature353:= as.integer( cliente_edad*ccaja_ahorro )]
dtrain[ ,feature354:= as.integer( cliente_edad*mcheques_depositados )]
dtrain[ ,feature355:= as.integer( cliente_edad*Visa_fechaalta )]
dtrain[ ,feature356:= as.integer( cliente_edad*mtarjeta_master_consumo )]
dtrain[ ,feature357:= as.integer( cliente_edad*ctarjeta_visa_transacciones )]
dtrain[ ,feature358:= as.integer( cliente_edad*Visa_mpagospesos )]
dtrain[ ,feature359:= as.integer( cliente_edad*mtarjeta_visa_consumo )]
dtrain[ ,feature360:= as.integer( cliente_edad*mpasivos_margen )]
dtrain[ ,feature361:= as.integer( cliente_edad*ccallcenter_transacciones )]
dtrain[ ,feature362:= as.integer( cliente_edad*cliente_edad )]
dtrain[ ,feature363:= as.integer( cliente_edad*mcaja_ahorro )]
dtrain[ ,feature364:= as.integer( cliente_edad*Visa_msaldototal )]
dtrain[ ,feature365:= as.integer( cliente_edad*ctrx_quarter )]
dtrain[ ,feature366:= as.integer( mcaja_ahorro*mpayroll )]
dtrain[ ,feature367:= as.integer( mcaja_ahorro*ccaja_ahorro )]
dtrain[ ,feature368:= as.integer( mcaja_ahorro*mcheques_depositados )]
dtrain[ ,feature369:= as.integer( mcaja_ahorro*Visa_fechaalta )]
dtrain[ ,feature370:= as.integer( mcaja_ahorro*mtarjeta_master_consumo )]
dtrain[ ,feature371:= as.integer( mcaja_ahorro*ctarjeta_visa_transacciones )]
dtrain[ ,feature372:= as.integer( mcaja_ahorro*Visa_mpagospesos )]
dtrain[ ,feature373:= as.integer( mcaja_ahorro*mtarjeta_visa_consumo )]
dtrain[ ,feature374:= as.integer( mcaja_ahorro*mpasivos_margen )]
dtrain[ ,feature375:= as.integer( mcaja_ahorro*ccallcenter_transacciones )]
dtrain[ ,feature376:= as.integer( mcaja_ahorro*cliente_edad )]
dtrain[ ,feature377:= as.integer( mcaja_ahorro*mcaja_ahorro )]
dtrain[ ,feature378:= as.integer( mcaja_ahorro*Visa_msaldototal )]
dtrain[ ,feature379:= as.integer( mcaja_ahorro*ctrx_quarter )]
dtrain[ ,feature380:= as.integer( Visa_msaldototal*mpayroll )]
dtrain[ ,feature381:= as.integer( Visa_msaldototal*ccaja_ahorro )]
dtrain[ ,feature382:= as.integer( Visa_msaldototal*mcheques_depositados )]
dtrain[ ,feature383:= as.integer( Visa_msaldototal*Visa_fechaalta )]
dtrain[ ,feature384:= as.integer( Visa_msaldototal*mtarjeta_master_consumo )]
dtrain[ ,feature385:= as.integer( Visa_msaldototal*ctarjeta_visa_transacciones )]
dtrain[ ,feature386:= as.integer( Visa_msaldototal*Visa_mpagospesos )]
dtrain[ ,feature387:= as.integer( Visa_msaldototal*mtarjeta_visa_consumo )]
dtrain[ ,feature388:= as.integer( Visa_msaldototal*mpasivos_margen )]
dtrain[ ,feature389:= as.integer( Visa_msaldototal*ccallcenter_transacciones )]
dtrain[ ,feature390:= as.integer( Visa_msaldototal*cliente_edad )]
dtrain[ ,feature391:= as.integer( Visa_msaldototal*mcaja_ahorro )]
dtrain[ ,feature392:= as.integer( Visa_msaldototal*Visa_msaldototal )]


dapply  <- dataset[ foto_mes==202103, ]  #defino donde voy a aplicar el modelo

#Creo ranking de variables #frankv(DT, cols="x", na.last="keep")

frankv(dapply, cols="ctrx_quarter", na.last="keep")
frankv(dapply, cols="mcuentas_saldo", na.last="keep")
frankv(dapply, cols="cdescubierto_preacordado", na.last="keep")
frankv(dapply, cols="mprestamos_personales", na.last="keep")
frankv(dapply, cols="active_quarter", na.last="keep")
frankv(dapply, cols="cprestamos_personales", na.last="keep")
frankv(dapply, cols="mcaja_ahorro", na.last="keep")
frankv(dapply, cols="mcuenta_corriente", na.last="keep")
frankv(dapply, cols="mactivos_margen", na.last="keep")
frankv(dapply, cols="ccomisiones_otras", na.last="keep")
frankv(dapply, cols="mpasivos_margen", na.last="keep")
frankv(dapply, cols="mtarjeta_visa_consumo", na.last="keep")
frankv(dapply, cols="Visa_msaldototal", na.last="keep")
frankv(dapply, cols="Visa_msaldopesos", na.last="keep")
frankv(dapply, cols="ctarjeta_visa_transacciones", na.last="keep")
frankv(dapply, cols="mcomisiones", na.last="keep")
frankv(dapply, cols="cliente_antiguedad", na.last="keep")
frankv(dapply, cols="mcomisiones_otras", na.last="keep")
frankv(dapply, cols="mpayroll", na.last="keep")


#Creo nuevas features
dapply[ ,feature1:= as.integer( ctrx_quarter+ctrx_quarter )]
dapply[ ,feature2:= as.integer( ctrx_quarter+mpayroll )]
dapply[ ,feature3:= as.integer( ctrx_quarter+ccaja_ahorro )]
dapply[ ,feature4:= as.integer( ctrx_quarter+mcheques_depositados )]
dapply[ ,feature5:= as.integer( ctrx_quarter+Visa_fechaalta )]
dapply[ ,feature6:= as.integer( ctrx_quarter+mtarjeta_master_consumo )]
dapply[ ,feature7:= as.integer( ctrx_quarter+ctarjeta_visa_transacciones )]
dapply[ ,feature8:= as.integer( ctrx_quarter+Visa_mpagospesos )]
dapply[ ,feature9:= as.integer( ctrx_quarter+mtarjeta_visa_consumo )]
dapply[ ,feature10:= as.integer( ctrx_quarter+mpasivos_margen )]
dapply[ ,feature11:= as.integer( ctrx_quarter+ccallcenter_transacciones )]
dapply[ ,feature12:= as.integer( ctrx_quarter+cliente_edad )]
dapply[ ,feature13:= as.integer( ctrx_quarter+mcaja_ahorro )]
dapply[ ,feature14:= as.integer( ctrx_quarter+Visa_msaldototal )]
dapply[ ,feature15:= as.integer( mpayroll+ctrx_quarter )]
dapply[ ,feature16:= as.integer( mpayroll+mpayroll )]
dapply[ ,feature17:= as.integer( mpayroll+ccaja_ahorro )]
dapply[ ,feature18:= as.integer( mpayroll+mcheques_depositados )]
dapply[ ,feature19:= as.integer( mpayroll+Visa_fechaalta )]
dapply[ ,feature20:= as.integer( mpayroll+mtarjeta_master_consumo )]
dapply[ ,feature21:= as.integer( mpayroll+ctarjeta_visa_transacciones )]
dapply[ ,feature22:= as.integer( mpayroll+Visa_mpagospesos )]
dapply[ ,feature23:= as.integer( mpayroll+mtarjeta_visa_consumo )]
dapply[ ,feature24:= as.integer( mpayroll+mpasivos_margen )]
dapply[ ,feature25:= as.integer( mpayroll+ccallcenter_transacciones )]
dapply[ ,feature26:= as.integer( mpayroll+cliente_edad )]
dapply[ ,feature27:= as.integer( mpayroll+mcaja_ahorro )]
dapply[ ,feature28:= as.integer( mpayroll+Visa_msaldototal )]
dapply[ ,feature29:= as.integer( ccaja_ahorro+ctrx_quarter )]
dapply[ ,feature30:= as.integer( ccaja_ahorro+mpayroll )]
dapply[ ,feature31:= as.integer( ccaja_ahorro+ccaja_ahorro )]
dapply[ ,feature32:= as.integer( ccaja_ahorro+mcheques_depositados )]
dapply[ ,feature33:= as.integer( ccaja_ahorro+Visa_fechaalta )]
dapply[ ,feature34:= as.integer( ccaja_ahorro+mtarjeta_master_consumo )]
dapply[ ,feature35:= as.integer( ccaja_ahorro+ctarjeta_visa_transacciones )]
dapply[ ,feature36:= as.integer( ccaja_ahorro+Visa_mpagospesos )]
dapply[ ,feature37:= as.integer( ccaja_ahorro+mtarjeta_visa_consumo )]
dapply[ ,feature38:= as.integer( ccaja_ahorro+mpasivos_margen )]
dapply[ ,feature39:= as.integer( ccaja_ahorro+ccallcenter_transacciones )]
dapply[ ,feature40:= as.integer( ccaja_ahorro+cliente_edad )]
dapply[ ,feature41:= as.integer( ccaja_ahorro+mcaja_ahorro )]
dapply[ ,feature42:= as.integer( ccaja_ahorro+Visa_msaldototal )]
dapply[ ,feature43:= as.integer( ccaja_ahorro+ctrx_quarter )]
dapply[ ,feature44:= as.integer( mcheques_depositados+mpayroll )]
dapply[ ,feature45:= as.integer( mcheques_depositados+ccaja_ahorro )]
dapply[ ,feature46:= as.integer( mcheques_depositados+mcheques_depositados )]
dapply[ ,feature47:= as.integer( mcheques_depositados+Visa_fechaalta )]
dapply[ ,feature48:= as.integer( mcheques_depositados+mtarjeta_master_consumo )]
dapply[ ,feature49:= as.integer( mcheques_depositados+ctarjeta_visa_transacciones )]
dapply[ ,feature50:= as.integer( mcheques_depositados+Visa_mpagospesos )]
dapply[ ,feature51:= as.integer( mcheques_depositados+mtarjeta_visa_consumo )]
dapply[ ,feature52:= as.integer( mcheques_depositados+mpasivos_margen )]
dapply[ ,feature53:= as.integer( mcheques_depositados+ccallcenter_transacciones )]
dapply[ ,feature54:= as.integer( mcheques_depositados+cliente_edad )]
dapply[ ,feature55:= as.integer( mcheques_depositados+mcaja_ahorro )]
dapply[ ,feature56:= as.integer( mcheques_depositados+Visa_msaldototal )]
dapply[ ,feature57:= as.integer( mcheques_depositados+ctrx_quarter )]
dapply[ ,feature58:= as.integer( Visa_fechaalta+mpayroll )]
dapply[ ,feature59:= as.integer( Visa_fechaalta+ccaja_ahorro )]
dapply[ ,feature60:= as.integer( Visa_fechaalta+mcheques_depositados )]
dapply[ ,feature61:= as.integer( Visa_fechaalta+Visa_fechaalta )]
dapply[ ,feature62:= as.integer( Visa_fechaalta+mtarjeta_master_consumo )]
dapply[ ,feature63:= as.integer( Visa_fechaalta+ctarjeta_visa_transacciones )]
dapply[ ,feature64:= as.integer( Visa_fechaalta+Visa_mpagospesos )]
dapply[ ,feature65:= as.integer( Visa_fechaalta+mtarjeta_visa_consumo )]
dapply[ ,feature66:= as.integer( Visa_fechaalta+mpasivos_margen )]
dapply[ ,feature67:= as.integer( Visa_fechaalta+ccallcenter_transacciones )]
dapply[ ,feature68:= as.integer( Visa_fechaalta+cliente_edad )]
dapply[ ,feature69:= as.integer( Visa_fechaalta+mcaja_ahorro )]
dapply[ ,feature70:= as.integer( Visa_fechaalta+Visa_msaldototal )]
dapply[ ,feature71:= as.integer( Visa_fechaalta+ctrx_quarter )]
dapply[ ,feature72:= as.integer( mtarjeta_master_consumo+mpayroll )]
dapply[ ,feature73:= as.integer( mtarjeta_master_consumo+ccaja_ahorro )]
dapply[ ,feature74:= as.integer( mtarjeta_master_consumo+mcheques_depositados )]
dapply[ ,feature75:= as.integer( mtarjeta_master_consumo+Visa_fechaalta )]
dapply[ ,feature76:= as.integer( mtarjeta_master_consumo+mtarjeta_master_consumo )]
dapply[ ,feature77:= as.integer( mtarjeta_master_consumo+ctarjeta_visa_transacciones )]
dapply[ ,feature78:= as.integer( mtarjeta_master_consumo+Visa_mpagospesos )]
dapply[ ,feature79:= as.integer( mtarjeta_master_consumo+mtarjeta_visa_consumo )]
dapply[ ,feature80:= as.integer( mtarjeta_master_consumo+mpasivos_margen )]
dapply[ ,feature81:= as.integer( mtarjeta_master_consumo+ccallcenter_transacciones )]
dapply[ ,feature82:= as.integer( mtarjeta_master_consumo+cliente_edad )]
dapply[ ,feature83:= as.integer( mtarjeta_master_consumo+mcaja_ahorro )]
dapply[ ,feature84:= as.integer( mtarjeta_master_consumo+Visa_msaldototal )]
dapply[ ,feature85:= as.integer( mtarjeta_master_consumo+ctrx_quarter )]
dapply[ ,feature86:= as.integer( ctarjeta_visa_transacciones+mpayroll )]
dapply[ ,feature87:= as.integer( ctarjeta_visa_transacciones+ccaja_ahorro )]
dapply[ ,feature88:= as.integer( ctarjeta_visa_transacciones+mcheques_depositados )]
dapply[ ,feature89:= as.integer( ctarjeta_visa_transacciones+Visa_fechaalta )]
dapply[ ,feature90:= as.integer( ctarjeta_visa_transacciones+mtarjeta_master_consumo )]
dapply[ ,feature91:= as.integer( ctarjeta_visa_transacciones+ctarjeta_visa_transacciones )]
dapply[ ,feature92:= as.integer( ctarjeta_visa_transacciones+Visa_mpagospesos )]
dapply[ ,feature93:= as.integer( ctarjeta_visa_transacciones+mtarjeta_visa_consumo )]
dapply[ ,feature94:= as.integer( ctarjeta_visa_transacciones+mpasivos_margen )]
dapply[ ,feature95:= as.integer( ctarjeta_visa_transacciones+ccallcenter_transacciones )]
dapply[ ,feature96:= as.integer( ctarjeta_visa_transacciones+cliente_edad )]
dapply[ ,feature97:= as.integer( ctarjeta_visa_transacciones+mcaja_ahorro )]
dapply[ ,feature98:= as.integer( ctarjeta_visa_transacciones+Visa_msaldototal )]
dapply[ ,feature99:= as.integer( ctarjeta_visa_transacciones+ctrx_quarter )]
dapply[ ,feature100:= as.integer( Visa_mpagospesos+mpayroll )]
dapply[ ,feature101:= as.integer( Visa_mpagospesos+ccaja_ahorro )]
dapply[ ,feature102:= as.integer( Visa_mpagospesos+mcheques_depositados )]
dapply[ ,feature103:= as.integer( Visa_mpagospesos+Visa_fechaalta )]
dapply[ ,feature104:= as.integer( Visa_mpagospesos+mtarjeta_master_consumo )]
dapply[ ,feature105:= as.integer( Visa_mpagospesos+ctarjeta_visa_transacciones )]
dapply[ ,feature106:= as.integer( Visa_mpagospesos+Visa_mpagospesos )]
dapply[ ,feature107:= as.integer( Visa_mpagospesos+mtarjeta_visa_consumo )]
dapply[ ,feature108:= as.integer( Visa_mpagospesos+mpasivos_margen )]
dapply[ ,feature109:= as.integer( Visa_mpagospesos+ccallcenter_transacciones )]
dapply[ ,feature110:= as.integer( Visa_mpagospesos+cliente_edad )]
dapply[ ,feature111:= as.integer( Visa_mpagospesos+mcaja_ahorro )]
dapply[ ,feature112:= as.integer( Visa_mpagospesos+Visa_msaldototal )]
dapply[ ,feature113:= as.integer( Visa_mpagospesos+ctrx_quarter )]
dapply[ ,feature114:= as.integer( mtarjeta_visa_consumo+mpayroll )]
dapply[ ,feature115:= as.integer( mtarjeta_visa_consumo+ccaja_ahorro )]
dapply[ ,feature116:= as.integer( mtarjeta_visa_consumo+mcheques_depositados )]
dapply[ ,feature117:= as.integer( mtarjeta_visa_consumo+Visa_fechaalta )]
dapply[ ,feature118:= as.integer( mtarjeta_visa_consumo+mtarjeta_master_consumo )]
dapply[ ,feature119:= as.integer( mtarjeta_visa_consumo+ctarjeta_visa_transacciones )]
dapply[ ,feature120:= as.integer( mtarjeta_visa_consumo+Visa_mpagospesos )]
dapply[ ,feature121:= as.integer( mtarjeta_visa_consumo+mtarjeta_visa_consumo )]
dapply[ ,feature122:= as.integer( mtarjeta_visa_consumo+mpasivos_margen )]
dapply[ ,feature123:= as.integer( mtarjeta_visa_consumo+ccallcenter_transacciones )]
dapply[ ,feature124:= as.integer( mtarjeta_visa_consumo+cliente_edad )]
dapply[ ,feature125:= as.integer( mtarjeta_visa_consumo+mcaja_ahorro )]
dapply[ ,feature126:= as.integer( mtarjeta_visa_consumo+Visa_msaldototal )]
dapply[ ,feature127:= as.integer( mtarjeta_visa_consumo+ctrx_quarter )]
dapply[ ,feature128:= as.integer( mpasivos_margen+mpayroll )]
dapply[ ,feature129:= as.integer( mpasivos_margen+ccaja_ahorro )]
dapply[ ,feature130:= as.integer( mpasivos_margen+mcheques_depositados )]
dapply[ ,feature131:= as.integer( mpasivos_margen+Visa_fechaalta )]
dapply[ ,feature132:= as.integer( mpasivos_margen+mtarjeta_master_consumo )]
dapply[ ,feature133:= as.integer( mpasivos_margen+ctarjeta_visa_transacciones )]
dapply[ ,feature134:= as.integer( mpasivos_margen+Visa_mpagospesos )]
dapply[ ,feature135:= as.integer( mpasivos_margen+mtarjeta_visa_consumo )]
dapply[ ,feature136:= as.integer( mpasivos_margen+mpasivos_margen )]
dapply[ ,feature137:= as.integer( mpasivos_margen+ccallcenter_transacciones )]
dapply[ ,feature138:= as.integer( mpasivos_margen+cliente_edad )]
dapply[ ,feature139:= as.integer( mpasivos_margen+mcaja_ahorro )]
dapply[ ,feature140:= as.integer( mpasivos_margen+Visa_msaldototal )]
dapply[ ,feature141:= as.integer( mpasivos_margen+ctrx_quarter )]
dapply[ ,feature142:= as.integer( ccallcenter_transacciones+mpayroll )]
dapply[ ,feature143:= as.integer( ccallcenter_transacciones+ccaja_ahorro )]
dapply[ ,feature144:= as.integer( ccallcenter_transacciones+mcheques_depositados )]
dapply[ ,feature145:= as.integer( ccallcenter_transacciones+Visa_fechaalta )]
dapply[ ,feature146:= as.integer( ccallcenter_transacciones+mtarjeta_master_consumo )]
dapply[ ,feature147:= as.integer( ccallcenter_transacciones+ctarjeta_visa_transacciones )]
dapply[ ,feature148:= as.integer( ccallcenter_transacciones+Visa_mpagospesos )]
dapply[ ,feature149:= as.integer( ccallcenter_transacciones+mtarjeta_visa_consumo )]
dapply[ ,feature150:= as.integer( ccallcenter_transacciones+mpasivos_margen )]
dapply[ ,feature151:= as.integer( ccallcenter_transacciones+ccallcenter_transacciones )]
dapply[ ,feature152:= as.integer( ccallcenter_transacciones+cliente_edad )]
dapply[ ,feature153:= as.integer( ccallcenter_transacciones+mcaja_ahorro )]
dapply[ ,feature154:= as.integer( ccallcenter_transacciones+Visa_msaldototal )]
dapply[ ,feature155:= as.integer( ccallcenter_transacciones+ctrx_quarter )]
dapply[ ,feature156:= as.integer( cliente_edad+mpayroll )]
dapply[ ,feature157:= as.integer( cliente_edad+ccaja_ahorro )]
dapply[ ,feature158:= as.integer( cliente_edad+mcheques_depositados )]
dapply[ ,feature159:= as.integer( cliente_edad+Visa_fechaalta )]
dapply[ ,feature160:= as.integer( cliente_edad+mtarjeta_master_consumo )]
dapply[ ,feature161:= as.integer( cliente_edad+ctarjeta_visa_transacciones )]
dapply[ ,feature162:= as.integer( cliente_edad+Visa_mpagospesos )]
dapply[ ,feature163:= as.integer( cliente_edad+mtarjeta_visa_consumo )]
dapply[ ,feature164:= as.integer( cliente_edad+mpasivos_margen )]
dapply[ ,feature165:= as.integer( cliente_edad+ccallcenter_transacciones )]
dapply[ ,feature166:= as.integer( cliente_edad+cliente_edad )]
dapply[ ,feature167:= as.integer( cliente_edad+mcaja_ahorro )]
dapply[ ,feature168:= as.integer( cliente_edad+Visa_msaldototal )]
dapply[ ,feature169:= as.integer( cliente_edad+ctrx_quarter )]
dapply[ ,feature170:= as.integer( mcaja_ahorro+mpayroll )]
dapply[ ,feature171:= as.integer( mcaja_ahorro+ccaja_ahorro )]
dapply[ ,feature172:= as.integer( mcaja_ahorro+mcheques_depositados )]
dapply[ ,feature173:= as.integer( mcaja_ahorro+Visa_fechaalta )]
dapply[ ,feature174:= as.integer( mcaja_ahorro+mtarjeta_master_consumo )]
dapply[ ,feature175:= as.integer( mcaja_ahorro+ctarjeta_visa_transacciones )]
dapply[ ,feature176:= as.integer( mcaja_ahorro+Visa_mpagospesos )]
dapply[ ,feature177:= as.integer( mcaja_ahorro+mtarjeta_visa_consumo )]
dapply[ ,feature178:= as.integer( mcaja_ahorro+mpasivos_margen )]
dapply[ ,feature179:= as.integer( mcaja_ahorro+ccallcenter_transacciones )]
dapply[ ,feature180:= as.integer( mcaja_ahorro+cliente_edad )]
dapply[ ,feature181:= as.integer( mcaja_ahorro+mcaja_ahorro )]
dapply[ ,feature182:= as.integer( mcaja_ahorro+Visa_msaldototal )]
dapply[ ,feature183:= as.integer( mcaja_ahorro+ctrx_quarter )]
dapply[ ,feature184:= as.integer( Visa_msaldototal+mpayroll )]
dapply[ ,feature185:= as.integer( Visa_msaldototal+ccaja_ahorro )]
dapply[ ,feature186:= as.integer( Visa_msaldototal+mcheques_depositados )]
dapply[ ,feature187:= as.integer( Visa_msaldototal+Visa_fechaalta )]
dapply[ ,feature188:= as.integer( Visa_msaldototal+mtarjeta_master_consumo )]
dapply[ ,feature189:= as.integer( Visa_msaldototal+ctarjeta_visa_transacciones )]
dapply[ ,feature190:= as.integer( Visa_msaldototal+Visa_mpagospesos )]
dapply[ ,feature191:= as.integer( Visa_msaldototal+mtarjeta_visa_consumo )]
dapply[ ,feature192:= as.integer( Visa_msaldototal+mpasivos_margen )]
dapply[ ,feature193:= as.integer( Visa_msaldototal+ccallcenter_transacciones )]
dapply[ ,feature194:= as.integer( Visa_msaldototal+cliente_edad )]
dapply[ ,feature195:= as.integer( Visa_msaldototal+mcaja_ahorro )]
dapply[ ,feature196:= as.integer( Visa_msaldototal+Visa_msaldototal )]
dapply[ ,feature197:= as.integer( ctrx_quarter*ctrx_quarter )]
dapply[ ,feature198:= as.integer( ctrx_quarter*mpayroll )]
dapply[ ,feature199:= as.integer( ctrx_quarter*ccaja_ahorro )]
dapply[ ,feature200:= as.integer( ctrx_quarter*mcheques_depositados )]
dapply[ ,feature201:= as.integer( ctrx_quarter*Visa_fechaalta )]
dapply[ ,feature202:= as.integer( ctrx_quarter*mtarjeta_master_consumo )]
dapply[ ,feature203:= as.integer( ctrx_quarter*ctarjeta_visa_transacciones )]
dapply[ ,feature204:= as.integer( ctrx_quarter*Visa_mpagospesos )]
dapply[ ,feature205:= as.integer( ctrx_quarter*mtarjeta_visa_consumo )]
dapply[ ,feature206:= as.integer( ctrx_quarter*mpasivos_margen )]
dapply[ ,feature207:= as.integer( ctrx_quarter*ccallcenter_transacciones )]
dapply[ ,feature208:= as.integer( ctrx_quarter*cliente_edad )]
dapply[ ,feature209:= as.integer( ctrx_quarter*mcaja_ahorro )]
dapply[ ,feature210:= as.integer( ctrx_quarter*Visa_msaldototal )]
dapply[ ,feature211:= as.integer( mpayroll*ctrx_quarter )]
dapply[ ,feature212:= as.integer( mpayroll*mpayroll )]
dapply[ ,feature213:= as.integer( mpayroll*ccaja_ahorro )]
dapply[ ,feature214:= as.integer( mpayroll*mcheques_depositados )]
dapply[ ,feature215:= as.integer( mpayroll*Visa_fechaalta )]
dapply[ ,feature216:= as.integer( mpayroll*mtarjeta_master_consumo )]
dapply[ ,feature217:= as.integer( mpayroll*ctarjeta_visa_transacciones )]
dapply[ ,feature218:= as.integer( mpayroll*Visa_mpagospesos )]
dapply[ ,feature219:= as.integer( mpayroll*mtarjeta_visa_consumo )]
dapply[ ,feature220:= as.integer( mpayroll*mpasivos_margen )]
dapply[ ,feature221:= as.integer( mpayroll*ccallcenter_transacciones )]
dapply[ ,feature222:= as.integer( mpayroll*cliente_edad )]
dapply[ ,feature223:= as.integer( mpayroll*mcaja_ahorro )]
dapply[ ,feature224:= as.integer( mpayroll*Visa_msaldototal )]
dapply[ ,feature225:= as.integer( ccaja_ahorro*ctrx_quarter )]
dapply[ ,feature226:= as.integer( ccaja_ahorro*mpayroll )]
dapply[ ,feature227:= as.integer( ccaja_ahorro*ccaja_ahorro )]
dapply[ ,feature228:= as.integer( ccaja_ahorro*mcheques_depositados )]
dapply[ ,feature229:= as.integer( ccaja_ahorro*Visa_fechaalta )]
dapply[ ,feature230:= as.integer( ccaja_ahorro*mtarjeta_master_consumo )]
dapply[ ,feature231:= as.integer( ccaja_ahorro*ctarjeta_visa_transacciones )]
dapply[ ,feature232:= as.integer( ccaja_ahorro*Visa_mpagospesos )]
dapply[ ,feature233:= as.integer( ccaja_ahorro*mtarjeta_visa_consumo )]
dapply[ ,feature234:= as.integer( ccaja_ahorro*mpasivos_margen )]
dapply[ ,feature235:= as.integer( ccaja_ahorro*ccallcenter_transacciones )]
dapply[ ,feature236:= as.integer( ccaja_ahorro*cliente_edad )]
dapply[ ,feature237:= as.integer( ccaja_ahorro*mcaja_ahorro )]
dapply[ ,feature238:= as.integer( ccaja_ahorro*Visa_msaldototal )]
dapply[ ,feature239:= as.integer( ccaja_ahorro*ctrx_quarter )]
dapply[ ,feature240:= as.integer( mcheques_depositados*mpayroll )]
dapply[ ,feature241:= as.integer( mcheques_depositados*ccaja_ahorro )]
dapply[ ,feature242:= as.integer( mcheques_depositados*mcheques_depositados )]
dapply[ ,feature243:= as.integer( mcheques_depositados*Visa_fechaalta )]
dapply[ ,feature244:= as.integer( mcheques_depositados*mtarjeta_master_consumo )]
dapply[ ,feature245:= as.integer( mcheques_depositados*ctarjeta_visa_transacciones )]
dapply[ ,feature246:= as.integer( mcheques_depositados*Visa_mpagospesos )]
dapply[ ,feature247:= as.integer( mcheques_depositados*mtarjeta_visa_consumo )]
dapply[ ,feature248:= as.integer( mcheques_depositados*mpasivos_margen )]
dapply[ ,feature249:= as.integer( mcheques_depositados*ccallcenter_transacciones )]
dapply[ ,feature250:= as.integer( mcheques_depositados*cliente_edad )]
dapply[ ,feature251:= as.integer( mcheques_depositados*mcaja_ahorro )]
dapply[ ,feature252:= as.integer( mcheques_depositados*Visa_msaldototal )]
dapply[ ,feature253:= as.integer( mcheques_depositados*ctrx_quarter )]
dapply[ ,feature254:= as.integer( Visa_fechaalta*mpayroll )]
dapply[ ,feature255:= as.integer( Visa_fechaalta*ccaja_ahorro )]
dapply[ ,feature256:= as.integer( Visa_fechaalta*mcheques_depositados )]
dapply[ ,feature257:= as.integer( Visa_fechaalta*Visa_fechaalta )]
dapply[ ,feature258:= as.integer( Visa_fechaalta*mtarjeta_master_consumo )]
dapply[ ,feature259:= as.integer( Visa_fechaalta*ctarjeta_visa_transacciones )]
dapply[ ,feature260:= as.integer( Visa_fechaalta*Visa_mpagospesos )]
dapply[ ,feature261:= as.integer( Visa_fechaalta*mtarjeta_visa_consumo )]
dapply[ ,feature262:= as.integer( Visa_fechaalta*mpasivos_margen )]
dapply[ ,feature263:= as.integer( Visa_fechaalta*ccallcenter_transacciones )]
dapply[ ,feature264:= as.integer( Visa_fechaalta*cliente_edad )]
dapply[ ,feature265:= as.integer( Visa_fechaalta*mcaja_ahorro )]
dapply[ ,feature266:= as.integer( Visa_fechaalta*Visa_msaldototal )]
dapply[ ,feature267:= as.integer( Visa_fechaalta*ctrx_quarter )]
dapply[ ,feature268:= as.integer( mtarjeta_master_consumo*mpayroll )]
dapply[ ,feature269:= as.integer( mtarjeta_master_consumo*ccaja_ahorro )]
dapply[ ,feature270:= as.integer( mtarjeta_master_consumo*mcheques_depositados )]
dapply[ ,feature271:= as.integer( mtarjeta_master_consumo*Visa_fechaalta )]
dapply[ ,feature272:= as.integer( mtarjeta_master_consumo*mtarjeta_master_consumo )]
dapply[ ,feature273:= as.integer( mtarjeta_master_consumo*ctarjeta_visa_transacciones )]
dapply[ ,feature274:= as.integer( mtarjeta_master_consumo*Visa_mpagospesos )]
dapply[ ,feature275:= as.integer( mtarjeta_master_consumo*mtarjeta_visa_consumo )]
dapply[ ,feature276:= as.integer( mtarjeta_master_consumo*mpasivos_margen )]
dapply[ ,feature277:= as.integer( mtarjeta_master_consumo*ccallcenter_transacciones )]
dapply[ ,feature278:= as.integer( mtarjeta_master_consumo*cliente_edad )]
dapply[ ,feature279:= as.integer( mtarjeta_master_consumo*mcaja_ahorro )]
dapply[ ,feature280:= as.integer( mtarjeta_master_consumo*Visa_msaldototal )]
dapply[ ,feature281:= as.integer( mtarjeta_master_consumo*ctrx_quarter )]
dapply[ ,feature282:= as.integer( ctarjeta_visa_transacciones*mpayroll )]
dapply[ ,feature283:= as.integer( ctarjeta_visa_transacciones*ccaja_ahorro )]
dapply[ ,feature284:= as.integer( ctarjeta_visa_transacciones*mcheques_depositados )]
dapply[ ,feature285:= as.integer( ctarjeta_visa_transacciones*Visa_fechaalta )]
dapply[ ,feature286:= as.integer( ctarjeta_visa_transacciones*mtarjeta_master_consumo )]
dapply[ ,feature287:= as.integer( ctarjeta_visa_transacciones*ctarjeta_visa_transacciones )]
dapply[ ,feature288:= as.integer( ctarjeta_visa_transacciones*Visa_mpagospesos )]
dapply[ ,feature289:= as.integer( ctarjeta_visa_transacciones*mtarjeta_visa_consumo )]
dapply[ ,feature290:= as.integer( ctarjeta_visa_transacciones*mpasivos_margen )]
dapply[ ,feature291:= as.integer( ctarjeta_visa_transacciones*ccallcenter_transacciones )]
dapply[ ,feature292:= as.integer( ctarjeta_visa_transacciones*cliente_edad )]
dapply[ ,feature293:= as.integer( ctarjeta_visa_transacciones*mcaja_ahorro )]
dapply[ ,feature294:= as.integer( ctarjeta_visa_transacciones*Visa_msaldototal )]
dapply[ ,feature295:= as.integer( ctarjeta_visa_transacciones*ctrx_quarter )]
dapply[ ,feature296:= as.integer( Visa_mpagospesos*mpayroll )]
dapply[ ,feature297:= as.integer( Visa_mpagospesos*ccaja_ahorro )]
dapply[ ,feature298:= as.integer( Visa_mpagospesos*mcheques_depositados )]
dapply[ ,feature299:= as.integer( Visa_mpagospesos*Visa_fechaalta )]
dapply[ ,feature300:= as.integer( Visa_mpagospesos*mtarjeta_master_consumo )]
dapply[ ,feature301:= as.integer( Visa_mpagospesos*ctarjeta_visa_transacciones )]
dapply[ ,feature302:= as.integer( Visa_mpagospesos*Visa_mpagospesos )]
dapply[ ,feature303:= as.integer( Visa_mpagospesos*mtarjeta_visa_consumo )]
dapply[ ,feature304:= as.integer( Visa_mpagospesos*mpasivos_margen )]
dapply[ ,feature305:= as.integer( Visa_mpagospesos*ccallcenter_transacciones )]
dapply[ ,feature306:= as.integer( Visa_mpagospesos*cliente_edad )]
dapply[ ,feature307:= as.integer( Visa_mpagospesos*mcaja_ahorro )]
dapply[ ,feature308:= as.integer( Visa_mpagospesos*Visa_msaldototal )]
dapply[ ,feature309:= as.integer( Visa_mpagospesos*ctrx_quarter )]
dapply[ ,feature310:= as.integer( mtarjeta_visa_consumo*mpayroll )]
dapply[ ,feature311:= as.integer( mtarjeta_visa_consumo*ccaja_ahorro )]
dapply[ ,feature312:= as.integer( mtarjeta_visa_consumo*mcheques_depositados )]
dapply[ ,feature313:= as.integer( mtarjeta_visa_consumo*Visa_fechaalta )]
dapply[ ,feature314:= as.integer( mtarjeta_visa_consumo*mtarjeta_master_consumo )]
dapply[ ,feature315:= as.integer( mtarjeta_visa_consumo*ctarjeta_visa_transacciones )]
dapply[ ,feature316:= as.integer( mtarjeta_visa_consumo*Visa_mpagospesos )]
dapply[ ,feature317:= as.integer( mtarjeta_visa_consumo*mtarjeta_visa_consumo )]
dapply[ ,feature318:= as.integer( mtarjeta_visa_consumo*mpasivos_margen )]
dapply[ ,feature319:= as.integer( mtarjeta_visa_consumo*ccallcenter_transacciones )]
dapply[ ,feature320:= as.integer( mtarjeta_visa_consumo*cliente_edad )]
dapply[ ,feature321:= as.integer( mtarjeta_visa_consumo*mcaja_ahorro )]
dapply[ ,feature322:= as.integer( mtarjeta_visa_consumo*Visa_msaldototal )]
dapply[ ,feature323:= as.integer( mtarjeta_visa_consumo*ctrx_quarter )]
dapply[ ,feature324:= as.integer( mpasivos_margen*mpayroll )]
dapply[ ,feature325:= as.integer( mpasivos_margen*ccaja_ahorro )]
dapply[ ,feature326:= as.integer( mpasivos_margen*mcheques_depositados )]
dapply[ ,feature327:= as.integer( mpasivos_margen*Visa_fechaalta )]
dapply[ ,feature328:= as.integer( mpasivos_margen*mtarjeta_master_consumo )]
dapply[ ,feature329:= as.integer( mpasivos_margen*ctarjeta_visa_transacciones )]
dapply[ ,feature330:= as.integer( mpasivos_margen*Visa_mpagospesos )]
dapply[ ,feature331:= as.integer( mpasivos_margen*mtarjeta_visa_consumo )]
dapply[ ,feature332:= as.integer( mpasivos_margen*mpasivos_margen )]
dapply[ ,feature333:= as.integer( mpasivos_margen*ccallcenter_transacciones )]
dapply[ ,feature334:= as.integer( mpasivos_margen*cliente_edad )]
dapply[ ,feature335:= as.integer( mpasivos_margen*mcaja_ahorro )]
dapply[ ,feature336:= as.integer( mpasivos_margen*Visa_msaldototal )]
dapply[ ,feature337:= as.integer( mpasivos_margen*ctrx_quarter )]
dapply[ ,feature338:= as.integer( ccallcenter_transacciones*mpayroll )]
dapply[ ,feature339:= as.integer( ccallcenter_transacciones*ccaja_ahorro )]
dapply[ ,feature340:= as.integer( ccallcenter_transacciones*mcheques_depositados )]
dapply[ ,feature341:= as.integer( ccallcenter_transacciones*Visa_fechaalta )]
dapply[ ,feature342:= as.integer( ccallcenter_transacciones*mtarjeta_master_consumo )]
dapply[ ,feature343:= as.integer( ccallcenter_transacciones*ctarjeta_visa_transacciones )]
dapply[ ,feature344:= as.integer( ccallcenter_transacciones*Visa_mpagospesos )]
dapply[ ,feature345:= as.integer( ccallcenter_transacciones*mtarjeta_visa_consumo )]
dapply[ ,feature346:= as.integer( ccallcenter_transacciones*mpasivos_margen )]
dapply[ ,feature347:= as.integer( ccallcenter_transacciones*ccallcenter_transacciones )]
dapply[ ,feature348:= as.integer( ccallcenter_transacciones*cliente_edad )]
dapply[ ,feature349:= as.integer( ccallcenter_transacciones*mcaja_ahorro )]
dapply[ ,feature350:= as.integer( ccallcenter_transacciones*Visa_msaldototal )]
dapply[ ,feature351:= as.integer( ccallcenter_transacciones*ctrx_quarter )]
dapply[ ,feature352:= as.integer( cliente_edad*mpayroll )]
dapply[ ,feature353:= as.integer( cliente_edad*ccaja_ahorro )]
dapply[ ,feature354:= as.integer( cliente_edad*mcheques_depositados )]
dapply[ ,feature355:= as.integer( cliente_edad*Visa_fechaalta )]
dapply[ ,feature356:= as.integer( cliente_edad*mtarjeta_master_consumo )]
dapply[ ,feature357:= as.integer( cliente_edad*ctarjeta_visa_transacciones )]
dapply[ ,feature358:= as.integer( cliente_edad*Visa_mpagospesos )]
dapply[ ,feature359:= as.integer( cliente_edad*mtarjeta_visa_consumo )]
dapply[ ,feature360:= as.integer( cliente_edad*mpasivos_margen )]
dapply[ ,feature361:= as.integer( cliente_edad*ccallcenter_transacciones )]
dapply[ ,feature362:= as.integer( cliente_edad*cliente_edad )]
dapply[ ,feature363:= as.integer( cliente_edad*mcaja_ahorro )]
dapply[ ,feature364:= as.integer( cliente_edad*Visa_msaldototal )]
dapply[ ,feature365:= as.integer( cliente_edad*ctrx_quarter )]
dapply[ ,feature366:= as.integer( mcaja_ahorro*mpayroll )]
dapply[ ,feature367:= as.integer( mcaja_ahorro*ccaja_ahorro )]
dapply[ ,feature368:= as.integer( mcaja_ahorro*mcheques_depositados )]
dapply[ ,feature369:= as.integer( mcaja_ahorro*Visa_fechaalta )]
dapply[ ,feature370:= as.integer( mcaja_ahorro*mtarjeta_master_consumo )]
dapply[ ,feature371:= as.integer( mcaja_ahorro*ctarjeta_visa_transacciones )]
dapply[ ,feature372:= as.integer( mcaja_ahorro*Visa_mpagospesos )]
dapply[ ,feature373:= as.integer( mcaja_ahorro*mtarjeta_visa_consumo )]
dapply[ ,feature374:= as.integer( mcaja_ahorro*mpasivos_margen )]
dapply[ ,feature375:= as.integer( mcaja_ahorro*ccallcenter_transacciones )]
dapply[ ,feature376:= as.integer( mcaja_ahorro*cliente_edad )]
dapply[ ,feature377:= as.integer( mcaja_ahorro*mcaja_ahorro )]
dapply[ ,feature378:= as.integer( mcaja_ahorro*Visa_msaldototal )]
dapply[ ,feature379:= as.integer( mcaja_ahorro*ctrx_quarter )]
dapply[ ,feature380:= as.integer( Visa_msaldototal*mpayroll )]
dapply[ ,feature381:= as.integer( Visa_msaldototal*ccaja_ahorro )]
dapply[ ,feature382:= as.integer( Visa_msaldototal*mcheques_depositados )]
dapply[ ,feature383:= as.integer( Visa_msaldototal*Visa_fechaalta )]
dapply[ ,feature384:= as.integer( Visa_msaldototal*mtarjeta_master_consumo )]
dapply[ ,feature385:= as.integer( Visa_msaldototal*ctarjeta_visa_transacciones )]
dapply[ ,feature386:= as.integer( Visa_msaldototal*Visa_mpagospesos )]
dapply[ ,feature387:= as.integer( Visa_msaldototal*mtarjeta_visa_consumo )]
dapply[ ,feature388:= as.integer( Visa_msaldototal*mpasivos_margen )]
dapply[ ,feature389:= as.integer( Visa_msaldototal*ccallcenter_transacciones )]
dapply[ ,feature390:= as.integer( Visa_msaldototal*cliente_edad )]
dapply[ ,feature391:= as.integer( Visa_msaldototal*mcaja_ahorro )]
dapply[ ,feature392:= as.integer( Visa_msaldototal*Visa_msaldototal )]



# Entreno el modelo
# obviamente rpart no puede ver  clase_ternaria para predecir  clase_binaria
#  #no utilizo Visa_mpagado ni  mcomisiones_mantenimiento por drifting

modelo  <- rpart(formula=   "clase_binaria ~ .  -clase_ternaria ", #-ctrx_quarter
                 data=      dtrain,  #los datos donde voy a entrenar
                 xval=         0,
                 cp=          -1,   #-0.89 -0.54
                 minsplit=   797,   # 621  1073
                 minbucket=  163,   # 309   278
                 maxdepth=     6 )  #  12     9

#grafico el arbol
prp(modelo, extra=101, digits=5, branch=1, type=4, varlen=0, faclen=0)

rpart.plot(modelo)

vector_importantes <- names(modelo$variable.importance)

vector_importantes

#----------------------------------------------------------------------------
# habilitar esta seccion si el Fiscal General  Alejandro Bolaños  lo autoriza
#----------------------------------------------------------------------------

# corrijo manualmente el drifting de  Visa_fultimo_cierre
dapply[ Visa_fultimo_cierre== 1, Visa_fultimo_cierre :=  4 ]
dapply[ Visa_fultimo_cierre== 7, Visa_fultimo_cierre := 11 ]
dapply[ Visa_fultimo_cierre==21, Visa_fultimo_cierre := 25 ]
dapply[ Visa_fultimo_cierre==14, Visa_fultimo_cierre := 18 ]
dapply[ Visa_fultimo_cierre==28, Visa_fultimo_cierre := 32 ]
dapply[ Visa_fultimo_cierre==35, Visa_fultimo_cierre := 39 ]
dapply[ Visa_fultimo_cierre> 39, Visa_fultimo_cierre := Visa_fultimo_cierre + 4 ]

# corrijo manualmente el drifting de  Visa_fultimo_cierre
dapply[ Master_fultimo_cierre== 1, Master_fultimo_cierre :=  4 ]
dapply[ Master_fultimo_cierre== 7, Master_fultimo_cierre := 11 ]
dapply[ Master_fultimo_cierre==21, Master_fultimo_cierre := 25 ]
dapply[ Master_fultimo_cierre==14, Master_fultimo_cierre := 18 ]
dapply[ Master_fultimo_cierre==28, Master_fultimo_cierre := 32 ]
dapply[ Master_fultimo_cierre==35, Master_fultimo_cierre := 39 ]
dapply[ Master_fultimo_cierre> 39, Master_fultimo_cierre := Master_fultimo_cierre + 4 ]


#aplico el modelo a los datos nuevos
prediccion  <- predict( object=  modelo,
                        newdata= dapply,
                        type = "prob")

#prediccion es una matriz con DOS columnas, llamadas "NO", "SI"
#cada columna es el vector de probabilidades 

#agrego a dapply una columna nueva que es la probabilidad de BAJA+2
dfinal  <- copy( dapply[ , list(numero_de_cliente) ] )
dfinal[ , prob_SI := prediccion[ , "SI"] ]


# por favor cambiar por una semilla propia
# que sino el Fiscal General va a impugnar la prediccion
set.seed(113111)  
dfinal[ , azar := runif( nrow(dapply) ) ]

# ordeno en forma descentente, y cuando coincide la probabilidad, al azar
setorder( dfinal, -prob_SI, azar )


dir.create( "./exp/" )
dir.create( "./exp/KA113111" )


for( corte  in  c( 8600, 8750, 8700, 8650, 8800, 8000 ) )
{
  #le envio a los  corte  mejores,  de mayor probabilidad de prob_SI
  dfinal[ , Predicted := 0L ]
  dfinal[ 1:corte , Predicted := 1L ]


  fwrite( dfinal[ , list(numero_de_cliente, Predicted) ], #solo los campos para Kaggle
           file= paste0( "./exp/KA113111/20220909_HT10_378_",  corte, ".csv"),
           sep=  "," )
}

